spring:
  application:
    name: webrise-test-project

  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
    username: "${SPRING_DATASOURCE_USERNAME}"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration,db/data_migration

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG